# Generated by Django 3.1.1 on 2020-09-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200914_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='occasion',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='package',
        ),
    ]
