# Generated by Django 3.1 on 2020-09-07 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='things_include',
            field=models.TextField(default=datetime.datetime(2020, 9, 7, 18, 5, 3, 645597, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
