# Generated by Django 3.1 on 2020-09-08 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200908_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=datetime.datetime(2020, 9, 8, 18, 9, 45, 841504, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
