# Generated by Django 3.1 on 2020-09-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200908_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
